### ISSUE TITLE
Unable to list APIs

### ISSUE THREAD

**Issue by abourdon** [gravitee-io/gravitee-raml-console#1]
Hi,

I just tried to test the API console by getting list of all apis without tunning anything. But when I clicked on the Get action, I did not have anything on my screen :

![selection_001](https://cloud.githubusercontent.com/assets/1511715/8594693/b6f97ca0-2643-11e5-8fb3-ed13ebc091d9.png)

When opening the browser's console, I could see the following errors :

![selection_002](https://cloud.githubusercontent.com/assets/1511715/8594702/c56eb084-2643-11e5-8773-285932fa12d3.png)
 
Is there an already declared API which could explain why we got a 404? In addition, is server can accept CORS?

Aurélien

**Comment by brasseld** [comment]
RAML has been used for design purpose and sharing API vision, not for having a try or playing with a dedicated instance.

Closing this ticket.
